-- for discord logs
Webhooks = {
    ['death'] = 'SET WEBHOOK HERE',
    ['revive'] = 'SET WEBHOOK HERE',
    ['kill'] = 'SET WEBHOOK HERE',
    ['heal'] = 'SET WEBHOOK HERE',
    ['alerts'] = 'SET WEBHOOK HERE',
    ['crutch'] = 'SET WEBHOOK HERE',
    ['wheelchair'] = 'SET WEBHOOK HERE',
    ['damages'] = 'SET WEBHOOK HERE',
    ['insurance'] = 'SET WEBHOOK HERE',
    ['interactions'] = 'SET WEBHOOK HERE',
    ['medicbag'] = 'SET WEBHOOK HERE',
}

-- for death cause
Weapons = {
    ['WEAPON_PISTOL'] = 'Pistol',
    ['WEAPON_COMBATPISTOL'] = 'Combat Pistol',
    ['WEAPON_APPISTOL'] = 'AP Pistol',
    ['WEAPON_PISTOL50'] = 'Pistol .50',
    ['WEAPON_SNSPISTOL'] = 'SNS Pistol',
    ['WEAPON_HEAVYPISTOL'] = 'Heavy Pistol',
    ['WEAPON_VINTAGEPISTOL'] = 'Vintage Pistol',
    ['WEAPON_MARKSMANPISTOL'] = 'Marksman Pistol',
    ['WEAPON_REVOLVER'] = 'Revolver',
    ['WEAPON_DOUBLEACTION'] = 'Double Action Revolver',
    ['WEAPON_RAYPISTOL'] = 'Up-n-Atomizer',
    ['WEAPON_CERAMICPISTOL'] = 'Ceramic Pistol',
    ['WEAPON_NAVYREVOLVER'] = 'Navy Revolver',
    ['WEAPON_STUNGUN'] = 'Stun Gun',
    ['WEAPON_FLAREGUN'] = 'Flare Gun',
    ['WEAPON_GADGETPISTOL'] = 'Gadget Pistol',
    ['WEAPON_MICROSMG'] = 'Micro SMG',
    ['WEAPON_SMG'] = 'SMG',
    ['WEAPON_ASSAULTSMG'] = 'Assault SMG',
    ['WEAPON_COMBATPDW'] = 'Combat PDW',
    ['WEAPON_MACHINEPISTOL'] = 'Machine Pistol',
    ['WEAPON_MINISMG'] = 'Mini SMG',
    ['WEAPON_RAYCARBINE'] = 'Unholy Hellbringer',
    ['WEAPON_PUMPSHOTGUN'] = 'Pump Shotgun',
    ['WEAPON_SAWNOFFSHOTGUN'] = 'Sawed-Off Shotgun',
    ['WEAPON_BULLPUPSHOTGUN'] = 'Bullpup Shotgun',
    ['WEAPON_MUSKET'] = 'Musket',
    ['WEAPON_HEAVYSHOTGUN'] = 'Heavy Shotgun',
    ['WEAPON_DBSHOTGUN'] = 'Double Barrel Shotgun',
    ['WEAPON_AUTOSHOTGUN'] = 'Sweeper Shotgun',
    ['WEAPON_ASSAULTRIFLE'] = 'Assault Rifle',
    ['WEAPON_CARBINERIFLE'] = 'Carbine Rifle',
    ['WEAPON_ADVANCEDRIFLE'] = 'Advanced Rifle',
    ['WEAPON_SPECIALCARBINE'] = 'Special Carbine',
    ['WEAPON_BULLPUPRIFLE'] = 'Bullpup Rifle',
    ['WEAPON_COMPACTRIFLE'] = 'Compact Rifle',
    ['WEAPON_MG'] = 'MG',
    ['WEAPON_COMBATMG'] = 'Combat MG',
    ['WEAPON_GUSENBERG'] = 'Gusenberg Sweeper',
    ['WEAPON_SNIPERRIFLE'] = 'Sniper Rifle',
    ['WEAPON_HEAVYSNIPER'] = 'Heavy Sniper',
    ['WEAPON_MARKSMANRIFLE'] = 'Marksman Rifle',
    ['WEAPON_RPG'] = 'RPG',
    ['WEAPON_GRENADELAUNCHER'] = 'Grenade Launcher',
    ['WEAPON_MINIGUN'] = 'Minigun',
    ['WEAPON_FIREWORK'] = 'Firework Launcher',
    ['WEAPON_RAILGUN'] = 'Railgun',
    ['WEAPON_HOMINGLAUNCHER'] = 'Homing Launcher',
    ['WEAPON_COMPACTLAUNCHER'] = 'Compact Grenade Launcher',
    ['WEAPON_RAYMINIGUN'] = 'Widowmaker',
    ['WEAPON_GRENADE'] = 'Grenade',
    ['WEAPON_STICKYBOMB'] = 'Sticky Bomb',
    ['WEAPON_PROXMINE'] = 'Proximity Mine',
    ['WEAPON_SMOKEGRENADE'] = 'Smoke Grenade',
    ['WEAPON_BZGAS'] = 'BZ Gas',
    ['WEAPON_MOLOTOV'] = 'Molotov Cocktail',
    ['WEAPON_FIREEXTINGUISHER'] = 'Fire Extinguisher',
    ['WEAPON_PETROLCAN'] = 'Jerry Can',
    ['WEAPON_SNOWBALL'] = 'Snowball',
    ['WEAPON_FLARE'] = 'Flare',
    ['WEAPON_BALL'] = 'Baseball Bat',
    ['WEAPON_CROWBAR'] = 'Crowbar',
    ['WEAPON_GOLFCLUB'] = 'Golf Club',
    ['WEAPON_HAMMER'] = 'Hammer',
    ['WEAPON_BAT'] = 'Bat',
    ['WEAPON_KNUCKLE'] = 'Brass Knuckles',
    ['WEAPON_KNIFE'] = 'Knife',
    ['WEAPON_MACHETE'] = 'Machete',
    ['WEAPON_SWITCHBLADE'] = 'Switchblade',
    ['WEAPON_WRENCH'] = 'Pipe Wrench',
    ['WEAPON_BATTLEAXE'] = 'Battle Axe',
    ['WEAPON_POOLCUE'] = 'Pool Cue',
    ['WEAPON_STONE_HATCHET'] = 'Stone Hatchet',
    ['WEAPON_FLASHLIGHT'] = 'Flashlight',
    ['WEAPON_NIGHTSTICK'] = 'Nightstick',
}

DeathCauses = {
    ['0'] = 'Unknown',
}

Citizen.CreateThread(function()
    for model, label in pairs(Weapons) do
        DeathCauses[tostring(GetHashKey(model))] = label
    end
end)