Config = {}

Config.TimerResetHours = 1 -- số giờ để reset giá
Config.Timezone = 7 -- UTC+7 cho Việt Nam

Config.MarketNPCs = {   
    {
        id = "EmsItems1", 
        enabled = true,
        label = "Dụng Cụ",
        ped = `s_m_m_paramedic_01`,
        coords = vector4(-487.41, -1010.70, 24.29, 178.61),
        type = "buy",
        items = {
            {name = "radio", label = "Bộ Đàm", buyPrice = 1000, sellMin = nil, sellMax = nil},
            {name = "job_card", label = "Thẻ Ngành", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "megaphone", label = "Loa", buyPrice = 100, sellMin = nil, sellMax = nil},
            {name = "medicbag", label = "Túi Y Tế", buyPrice = 3000, sellMin = nil, sellMax = nil},
            {name = "ambulance_gps", label = "GPS Xe", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "wheelchair", label = "Xe Lăn", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "crutch", label = "Nạng Chống", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "stretcher", label = "Cáng Cứu Thương", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "bodybag", label = "Túi Đựng Thi Thể", buyPrice = 100, sellMin = nil, sellMax = nil},
            {name = "tablet", label = "Máy Tính Bảng", buyPrice = 100, sellMin = nil, sellMax = nil},
        },
        requiredJob = {
            ["ambulance"] = 2,
        }
    },     
    {
        id = "newsitems", 
        enabled = true,
        label = "Dụng Cụ",
        ped = `a_m_o_soucent_01`,
        coords = vector4(-1056.97, -231.69, 44.02, 205.01),
        type = "buy",
        items = {
            {name = "news_camera", label = "Máy Quay", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "news_mic", label = "Microphone", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "news_bmicrophone", label = "Microphone Cần Câu", buyPrice = 500, sellMin = nil, sellMax = nil},
            {name = "job_card", label = "Thẻ Ngành", buyPrice = 500, sellMin = nil, sellMax = nil},
        },
        requiredJob = {
            ["lsnews"] = 2,
        }
    },  
    {
        id = "EmsItems", 
        enabled = true,
        label = "Dụng Cụ",
        ped = `s_m_m_paramedic_01`,
        coords = vector4(-487.84, -1005.00, 24.29, 0.00),
        type = "buy",
        items = {
            {name = "bandage", label = "Băng Gạc", buyPrice = 100, sellMin = nil, sellMax = nil},
            -- {name = "gauze", label = "Gạc Y Tế", buyPrice = 200, sellMin = nil, sellMax = nil},
            -- {name = "adrenaline", label = "Adrenaline", buyPrice = 200, sellMin = nil, sellMax = nil},
            -- {name = "cyclonamine", label = "Cyclonamine", buyPrice = 200, sellMin = nil, sellMax = nil},
            -- {name = "tourniquet", label = "Dây Caro", buyPrice = 200, sellMin = nil, sellMax = nil},
        }
    }, 
    {
        id = "PoliceItems", 
        enabled = true,
        label = "Dụng Cụ",
        ped = `s_m_y_cop_01`,
        coords = vector4(480.31, -996.71, 30.69, 90.40),
        type = "buy",
        items = {
            {name = "ifak", label = "ifak", buyPrice = 10, sellMin = nil, sellMax = nil, grade = 0},
            {name = "radio", label = "Bộ Đàm", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "job_card", label = "Thẻ Ngành", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "handcuffs", label = "Còng", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 2},
            {name = "weapon_colbaton", label = "Baton", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "weapon_stungun", label = "Taser", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 2},
            {name = "armor_plate2", label = "Giáp Nặng", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 4},
            {name = "megaphone", label = "Loa", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 2},
            {name = "weapon_flashlight", label = "Đèn Pin", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "weapon_glock22", label = "Glock 22", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 7},
            {name = "weapon_m9", label = "Beretta M9A3", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 7},
            {name = "weapon_mp9", label = "MP9", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 7},
            {name = "weapon_remington", label = "Remington 870", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 7},
            {name = "weapon_hk416", label = "HK-416", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 7},
            {name = "weapon_ar15", label = "AR-15", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 7},
            {name = "weapon_flashbang", label = "Flashbang", buyPrice = 2000, sellMin = nil, sellMax = nil, grade = 7},
            -- {name = "weapon_M110", label = "M110", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 11},
            {name = "ammo-9", label = "9mm", buyPrice = 1, sellMin = nil, sellMax = nil, grade = 7},
            {name = "ammo-45", label = ".45 ACP", buyPrice = 1, sellMin = nil, sellMax = nil, grade = 7},
            {name = "ammo-shotgun", label = "12 Gauge", buyPrice = 1, sellMin = nil, sellMax = nil, grade = 7},
            {name = "ammo-rifle", label = "5.56x45", buyPrice = 1, sellMin = nil, sellMax = nil, grade = 7},
            -- {name = "ammo-sniper", label = "7.62x51", buyPrice = 1, sellMin = nil, sellMax = nil, grade = 11},
            {name = "tablet", label = "tablet", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "bodycam", label = "Bodycam", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "dashcam", label = "Dashcam", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 1},
            {name = "drone", label = "Drone", buyPrice = 200, sellMin = nil, sellMax = nil, grade = 4},
            {name = "empty_evidence_bag", label = "Túi Vật Chứng", buyPrice = 1, sellMin = nil, sellMax = nil, grade = 0},
            {name = "crimecamera", label = "Máy Ảnh", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0},
            {name = "contract", label = "Giấy Chuyển Nhượng Xe", buyPrice = 20000, sellMin = nil, sellMax = nil, grade = 2},
            {name = "mu_256_5_0", label = "Mũ Bảo Hiểm", buyPrice = 100, sellMin = nil, sellMax = nil, grade = 0, type = 'clothing'},

        },
        requiredJob = {
            ["police"] = 0,
        }
    }, 
    {
        id = "market_24/7_1",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(-47.37, -1758.77, 29.42, 46.47),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_2",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(24.4, -1347.54, 29.5, 270.6),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_3",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(-706.07, -914.38, 19.22, 91.77),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_4",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(-1221.39, -908.0, 12.33, 39.12),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_5",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(2677.87, 3279.43, 55.24, 333.05),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_6",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(372.42, 326.12, 103.57, 261.85),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_7",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(-3039.41, 584.39, 7.91, 17.53),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_8",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(1960.01, 3740.01, 32.34, 307.41),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_9",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(1697.01, 4923.58, 42.06, 320.42),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_10",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(1728.05, 6415.59, 35.04, 236.69),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    }, 
    {
        id = "market_24/7_11",
        enabled = true,
        label = "Tạp Hóa",
        ped = `a_m_m_fatlatin_01`,
        coords = vector4(188.81, -889.07, 30.71, 248.16),
        type = "both",
        items = {
            {name = "phone", label = "Phone", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "scissors", label = "Cây Kéo", buyPrice = 200, sellMin = nil, sellMax = nil},
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "cleaning_kit", label = "Bộ Vệ Sinh Xe", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "anchovy", label = "Cá cơm", buyPrice = nil, sellMin = 20, sellMax = 30},
            {name = "trout", label = "Cá hồi suối", buyPrice = nil, sellMin = 26, sellMax = 38},
            {name = "haddock", label = "Cá tuyết vân đen", buyPrice = nil, sellMin = 36, sellMax = 50},
            {name = "salmon", label = "Cá hồi", buyPrice = nil, sellMin = 46, sellMax = 65},
            {name = "grouper", label = "Cá mú", buyPrice = nil, sellMin = 65, sellMax = 87},
            {name = "piranha", label = "Cá piranha", buyPrice = nil, sellMin = 87, sellMax = 116},
            {name = "red_snapper", label = "Cá hồng", buyPrice = nil, sellMin = 109, sellMax = 145},
            {name = "mahi_mahi", label = "Cá dorado", buyPrice = nil, sellMin = 138, sellMax = 188},
            {name = "tuna", label = "Cá ngừ đại dương", buyPrice = nil, sellMin = 203, sellMax = 275},
            {name = "shark", label = "Cá mập", buyPrice = nil, sellMin = 319, sellMax = 464},
            {name = "meatdeer", label = "Thịt hươu", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "hide_1star", label = "Da thú 1 sao", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "hide_2star", label = "Da thú 2 sao", buyPrice = nil, sellMin = 10, sellMax = 20},
            {name = "hide_3star", label = "Da thú 3 sao", buyPrice = nil, sellMin = 50, sellMax = 100},
            {name = "cotton", label = "Bông Cotton", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "metalscrap", label = "Kim Loại Vụn", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "plastic", label = "Nhựa", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "copper", label = "Đồng", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "iron", label = "Sắt", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "aluminum", label = "Nhôm", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "steel", label = "Thép", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "glass", label = "Kính", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "rubber", label = "Cao Su", buyPrice = nil, sellMin = 1, sellMax = 5},
            {name = "cut_paper", label = "Giấy", buyPrice = nil, sellMin = 20, sellMax = 30},
        }
    },
    {
        id = "market_prison",
        enabled = true,
        label = "Đồ Ăn & Thức Uống",
        ped = `mp_m_securoguard_01`,
        coords = vector4(1752.80, 2566.85, 45.57, 222.87),
        type = "buy",
        items = {
            {name = "burger", label = "Hamburger", buyPrice = 60, sellMin = nil, sellMax = nil},
            {name = "water", label = "Nước Suối", buyPrice = 50, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop1",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(-664.02, -933.51, 21.83, 177.34),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop2",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(811.98, -2159.08, 29.62, 357.88),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop3",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(1690.98, 3759.66, 34.71, 224.64),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop4",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(-332.79, 6083.77, 31.45, 224.75),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop5",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(254.46, -48.67, 69.94, 66.30),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop6",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(20.79, -1104.79, 29.80, 156.79),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop7",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(2570.01, 292.57, 108.73, 355.64),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop8",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(-1120.44, 2698.51, 18.55, 217.19),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "ammunation_shop9",
        enabled = true,
        label = "Mua Vũ Khí",
        ped = `s_m_y_ammucity_01`,
        coords = vector4(844.29, -1035.28, 28.19, 356.54),
        type = "buy",
        items = {
            {name = "weapon_knife", label = "Dao", buyPrice = 1500, sellMin = nil, sellMax = nil},
            {name = "weapon_katana", label = "Katana", buyPrice = 5000, sellMin = nil, sellMax = nil},
            {name = "weapon_sledgehammer", label = "Búa Tạ", buyPrice = 5000, sellMin = nil, sellMax = nil},
        }
    },
    -- {
    --     id = "houserobbery_shop",
    --     enabled = true,
    --     label = "Nói Chuyện Buôn Bán",
    --     ped = `g_m_y_armgoon_02`,
    --     coords = vector4(342.51, -2707.98, 1.71, 341.68),
    --     type = "buy",
    --     items = {
    --         {name = "house_locator", label = "Máy Định Vị Nhà", buyPrice = 200, sellMin = nil, sellMax = nil},
    --         {name = "powder", label = "Túi Bột", buyPrice = 200, sellMin = nil, sellMax = nil},
    --     }
    -- },
    -- {
    --     id = "houserobbery_shop2",
    --     enabled = true,
    --     label = "Nói Chuyện Buôn Bán",
    --     ped = `a_m_m_fatlatin_01`,
    --     coords = vector4(1336.84, 4362.86, 44.37, 222.43),
    --     type = "sell",
    --     blackmarket = true,
    --     items = {
    --         {name = "television", label = "Tivi Vuông", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "shoebox", label = "Hộp Giày", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "dj_deck", label = "Bàn DJ", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "console", label = "Máy Chơi Game", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "boombox", label = "Loa Di Động", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "bong", label = "Bình Hút", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "pogo", label = "Tượng Nghệ Thuật", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "flat_television", label = "Tivi Màn Phẳng", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "coffemachine", label = "Máy Pha Cà Phê", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "hairdryer", label = "Máy Sấy Tóc", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "j_phone", label = "Điện Thoại Bàn", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "sculpture", label = "Tượng Điêu Khắc", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "toiletry", label = "Đồ Vệ Sinh", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "laptop", label = "Máy Tính Xách Tay", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "monitor", label = "Màn Hình", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "printer", label = "Máy In", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "watch", label = "Đồng Hồ", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "toothpaste", label = "Kem Đánh Răng", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "soap", label = "Xà Phòng", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "shampoo", label = "Dầu Gội", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "romantic_book", label = "Tiểu Thuyết", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "necklace", label = "Dây Chuyền", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "gold_watch", label = "Đồng Hồ Vàng", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "gold_bracelet", label = "Vòng Tay Vàng", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "bracelet", label = "Vòng Tay", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "earings", label = "Bông Tai", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "book", label = "Sách", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "skull", label = "Đầu Lâu", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "pencil", label = "Bút Chì", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "notepad", label = "Sổ Tay", buyPrice = nil, sellMin = 100, sellMax = 200},
    --         {name = "tapeplayer", label = "Máy Phát Băng", buyPrice = nil, sellMin = 100, sellMax = 200},
    --     }
    -- },
    {
        id = "chopshop_shop",
        enabled = true,
        label = "Cửa Hàng Thiết Bị",
        ped = `g_m_y_ballasout_01`,
        coords = vector4(354.45, -2703.86, 1.71, 72.28),
        type = "buy",
        items = {
            {name = "weapon_digiscanner", label = "Máy Quét Tín Hiệu", buyPrice = 1000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "chopshop_shop2",
        enabled = true,
        label = "Thu Mua Phụ Tùng",
        ped = `a_m_m_salton_03`,
        coords = vector4(340.72, -2732.40, 5.99, 333.60),
        blackmarket = true,
        type = "sell",
        items = {
            {name = "car_wheel", label = "Bánh Xe", buyPrice = nil, sellMin = 3, sellMax = 7},
            {name = "car_door", label = "Cửa Xe", buyPrice = nil, sellMin = 5, sellMax = 9},
            {name = "radiator", label = "Két Nước", buyPrice = nil, sellMin = 7, sellMax = 11},
            {name = "trunk", label = "Cốp Xe", buyPrice = nil, sellMin = 7, sellMax = 11},
        }
    },
    {
        id = "gunshop1",
        enabled = true,
        label = "Cửa Hàng Súng Đạn",
        ped = `a_m_m_salton_01`,
        coords = vector4(379.18, 792.58, 190.41, 182.59),
        blackmarket = true,
        type = "buy",
        items = {
            {name = "weapon_g26", label = "Glock 26", buyPrice = 150, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "logshopfemale",
        enabled = true,
        label = "Cửa Hàng Quần Áo",
        ped = `a_f_y_business_01`,
        coords = vector4(201.27, -871.31, 30.71, 158.49),
        type = "buy",
        items = {
            {name = "quan_231_0_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "quan_231_1_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "quan_231_2_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "quan_231_3_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "quan_231_4_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "quan_231_5_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "quan_231_6_1", label = "Chân", buyPrice = 1, sellMin = nil, sellMax = nil, type = 'clothing'},
            {name = "hat_item", label = "Keo Vuốt Tóc", buyPrice = 1000, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "blackmarket1",
        enabled = true,
        label = "Cửa Hàng Dụng Cụ",
        ped = `a_m_m_salton_02`,
        coords = vector4(356.97, -2728.09, 5.99, 56.55),
        blackmarket = true,
        type = "buy",
        items = {
            {name = "blackphone", label = "Điện Thoại Vệ Tinh", buyPrice = 100, sellMin = nil, sellMax = nil},
            {name = "heistpack_drone", label = "Drone", buyPrice = 25, sellMin = nil, sellMax = nil},
            {name = "gasmask", label = "Mặt Nạ Phòng Độc", buyPrice = 10, sellMin = nil, sellMax = nil},
            {name = "heistpack_drill", label = "Máy Khoan Công Nghiệp", buyPrice = 20, sellMin = nil, sellMax = nil},
            -- {name = "weapon_hackingdevice", label = "Thiết Bị Hack", buyPrice = 50, sellMin = nil, sellMax = nil},
            {name = "heavy_rope", label = "Dây Thừng Cỡ Lớn", buyPrice = 10, sellMin = nil, sellMax = nil},
            {name = "heistpack_anchor", label = "Mỏ Neo", buyPrice = 10, sellMin = nil, sellMax = nil},
            {name = "heistpack_grinder", label = "Máy Cắt Cầm Tay", buyPrice = 50, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "weedshop1",
        enabled = true,
        label = "Cửa Hàng Nuôi Trồng",
        ped = `a_m_m_salton_01`,
        coords = vector4(355.64, -2731.34, 5.99, 57.01),
        blackmarket = true,
        type = "buy",
        items = {
            {name = "nutrient_solution", label = "Nước Dinh Dưỡng", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "fertilizer", label = "Phân Bón", buyPrice = 1, sellMin = nil, sellMax = nil},
        }
    },
    {
        id = "weedshop2",
        enabled = true,
        label = "Cửa Hàng Nuôi Trồng",
        ped = `a_m_m_salton_01`,
        coords = vector4(-1926.69, 1787.08, 172.60, 20.82),
        blackmarket = true,
        type = "buy",
        items = {
            {name = "herbal_oil", label = "Dầu Thảo Mộc", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "glycerin", label = "Glycerin", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "lavender_essence", label = "Hoa Oải Hương", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "curing_agent", label = "Chất Curing", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "flavor_oil", label = "Dầu Hương Liệu", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "herbal_mix", label = "Hỗn Hợp Thảo Mộc", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "citrus_extract", label = "Tinh Chất Cam", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "peppermint", label = "Lá Bạc Hà", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "ethanol", label = "Ethanol", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "lemon_essence", label = "Tinh Chất Chanh", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "stabilizer", label = "Chất Ổn Định", buyPrice = 1, sellMin = nil, sellMax = nil},
            {name = "vanilla_extract", label = "Tinh Chất Van", buyPrice = 1, sellMin = nil, sellMax = nil},
        }
    },

}

Config.MarketBlips = { 
    {coords = vector3(572.44, -1745.67, 29.25), sprite = 40, color = 3, scale = 0.9, display = 4, name = "Nhà Trọ"},
    {coords = vector3(-47.37, -1758.77, 29.42), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(24.4, -1347.54, 29.5), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(-706.07, -914.38, 19.22), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(-1221.39, -908.0, 12.33), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(2677.87, 3279.43, 55.24), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(372.42, 326.12, 103.57), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(-3039.41, 584.39, 7.91), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(1960.01, 3740.01, 32.34), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(1697.01, 4923.58, 42.06), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(1728.05, 6415.59, 35.04), sprite = 52, color = 2, scale = 0.6, display = 4, name = "Tạp Hóa"},
    {coords = vector3(-664.02, -933.51, 21.83), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(811.98, -2159.08, 29.62), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(1690.98, 3759.66, 34.71), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(-332.79, 6083.77, 31.45), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(254.46, -48.67, 69.94), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(20.79, -1104.79, 29.80), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(2570.01, 292.57, 108.73), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(-1120.44, 2698.51, 18.55), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(844.29, -1035.28, 28.19), sprite = 110, color = 1, scale = 0.6, display = 4, name = "Cửa Hàng Vũ Khí"},
    {coords = vector3(714.00, -964.77, 30.40), sprite = 850, color = 1, scale = 0.6, display = 4, name = "Xưởng May Balo"},
    {coords = vector3(-356.25, -133.68, 38.97), sprite = 446, color = 47, scale = 0.7, display = 4, name = "Sửa Xe"},
    {coords = vector3(2526.69, 4358.91, 40.06), sprite = 570, color = 0, scale = 0.7, display = 4, name = "Cánh Đồng Bông Cotton"},
    {coords = vector3(-580.10, 5369.02, 70.34), sprite = 85, color = 21, scale = 0.7, display = 4, name = "Trung Tâm Xử Lý Gỗ"},
}