Config = {}

Config.TicketItem = 'ticket'

Config.RarityValue = {
    rare      = 1,
    epic      = 3,
    legendary = 5,
}

Config.BonusItems = {
    ['balo_'] = 2,
}

Config.NPC = {
    model    = 'a_m_y_hasjew_01',
    coords   = vector4(139.61, -1040.63, 29.40, 54.13),
    scenario = 'WORLD_HUMAN_STAND_MOBILE',
}

Config.ClothingSlots = {
    mu          = { slot = 1,  slotType = 'hat',        label = 'Mũ',          componentId = 0,  componentType = 'props' },
    matna       = { slot = 2,  slotType = 'mask',       label = 'Mặt nạ',      componentId = 1,  componentType = 'component' },
    aokhoac     = { slot = 3,  slotType = 'jacket',     label = 'Áo khoác',    componentId = 11, componentType = 'component' },
    aotrong     = { slot = 4,  slotType = 'undershirt', label = 'Áo trong',    componentId = 8,  componentType = 'component' },
    tay         = { slot = 5,  slotType = 'gloves',     label = 'Găng tay',    componentId = 3,  componentType = 'component', selectorMode = true },
    quan        = { slot = 6,  slotType = 'pants',      label = 'Quần',        componentId = 4,  componentType = 'component' },
    giay        = { slot = 7,  slotType = 'shoes',      label = 'Giày',        componentId = 6,  componentType = 'component' },
    kinh        = { slot = 8,  slotType = 'glasses',    label = 'Kính',        componentId = 1,  componentType = 'props' },
    khuyentai   = { slot = 9,  slotType = 'ear',        label = 'Khuyên tai',  componentId = 2,  componentType = 'props' },
    daychuyen   = { slot = 10, slotType = 'necklace',   label = 'Dây chuyền',  componentId = 7,  componentType = 'component' },
    balo        = { slot = 11, slotType = 'backpack',   label = 'Ba lô',       componentId = 5,  componentType = 'component' },
    giap        = { slot = 12, slotType = 'vest',       label = 'Giáp',        componentId = 9,  componentType = 'component' },
    dongho      = { slot = 13, slotType = 'watch',      label = 'Đồng hồ',     componentId = 6,  componentType = 'props' },
    vongtay     = { slot = 14, slotType = 'bracelet',   label = 'Vòng tay',    componentId = 7,  componentType = 'props' },
    huyhieu     = { slot = 15, slotType = 'decal',      label = 'Huy hiệu',    componentId = 10, componentType = 'component' },
}


Config.ShopItems = {
    {
        id          = 1,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Trắng)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 0,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 2,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Đỏ)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 3,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 3,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Xanh Dương)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 4,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 4,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Xanh Lá)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 5,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 5,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Vàng)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 6,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 6,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Tím)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 7,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 7,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Cam)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 8,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 8,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Xanh Cyan)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 9,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 9,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Đen)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 10,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 10,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Hồng)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 11,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 10,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Hồng)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 11,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 10,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 1 (Hồng)',
        slotType    = 'necklace',
        drawableId  = 194,
        textureId   = 11,
        gender      = 0,
        price       = 200,
    },
    {
        id          = 11,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 2 (Trắng)',
        slotType    = 'necklace',
        drawableId  = 235,
        textureId   = 0,
        gender      = 0,
        price       = 500,
    },
    {
        id          = 12,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 2 (Vàng)',
        slotType    = 'necklace',
        drawableId  = 235,
        textureId   = 1,
        gender      = 0,
        price       = 500,
    },
    {
        id          = 13,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 2 (Hồng)',
        slotType    = 'necklace',
        drawableId  = 235,
        textureId   = 2,
        gender      = 0,
        price       = 500,
    },
    {
        id          = 14,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 3 (Trắng)',
        slotType    = 'necklace',
        drawableId  = 241,
        textureId   = 0,
        gender      = 0,
        price       = 500,
    },
    {
        id          = 15,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 3 (Vàng)',
        slotType    = 'necklace',
        drawableId  = 241,
        textureId   = 1,
        gender      = 0,
        price       = 500,
    },
    {
        id          = 16,
        name        = 'daychuyen',      
        label       = 'Dây chuyền 3 (Hồng)',
        slotType    = 'necklace',
        drawableId  = 241,
        textureId   = 2,
        gender      = 0,
        price       = 500,
    },
}